# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicativo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=70)),
                ('altitud', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Ciudad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tmed', models.FloatField()),
                ('prec', models.FloatField()),
                ('tmin', models.FloatField()),
                ('hora_tmin', models.DateField()),
                ('tmax', models.FloatField()),
                ('hora_tmax', models.DateField()),
                ('direction', models.FloatField()),
                ('vel_media', models.FloatField()),
                ('racha', models.FloatField()),
                ('hora_racha', models.DateField()),
                ('sol', models.FloatField()),
                ('pres_max', models.FloatField()),
                ('pres_min', models.FloatField()),
                ('hora_pres_min', models.DateField()),
                ('hora_pres_max', models.DateField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.Estacion')),
            ],
        ),
    ]
