# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora_pres_max',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_pres_min',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_racha',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_tmax',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_tmin',
            field=models.TimeField(),
        ),
    ]
