# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=0)),
                ('avalible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure_Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('simbol', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Family')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon')),
                ('recomended_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Staff_Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf_role_description', models.CharField(choices=[('W', 'Camarero'), ('K', 'Cocinero'), ('B', 'Barman')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Provider')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant')),
                ('staff_role_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Ref_Staff_Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supply_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type_table', models.CharField(choices=[('M', 'Mesa'), ('T', 'Terraza'), ('B', 'Barra')], max_length=1)),
                ('is_available', models.BooleanField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meal', models.DateField(db_index=True)),
                ('cost_of_meal', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Staff')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Table')),
            ],
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Ticket_Resume'),
        ),
        migrations.AddField(
            model_name='service',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Supply'),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Product_Class'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Supply'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='mesure_unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Mesure_Unity'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Supply'),
        ),
        migrations.AddField(
            model_name='family',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon'),
        ),
    ]
