# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Family'),
        ),
    ]
