# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=30)),
                ('menu_item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Menu_Item')),
            ],
        ),
    ]
