# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nif',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
