# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0002_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
        migrations.RenameModel(
            old_name='Meal_Dishes',
            new_name='Meal_Dish',
        ),
        migrations.RenameModel(
            old_name='Ref_Staff_Roles',
            new_name='Ref_Staff_Rol',
        ),
    ]
