# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0002_restaurant_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_without_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticket_resume',
            name='cost_without_tax',
            field=models.FloatField(default=0),
        ),
    ]
