# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0003_auto_20170501_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Family')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.AddField(
            model_name='product_family',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Product'),
        ),
    ]
