# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0003_auto_20170228_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref_staff_rol',
            name='staf_role_description',
            field=models.CharField(choices=[('W', 'Camarero'), ('K', 'Cocinero'), ('B', 'Barman')], max_length=1),
        ),
    ]
