# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0004_auto_20170228_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menu_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Menu_Category'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
