# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0004_auto_20170502_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_family',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant'),
        ),
    ]
