# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0004_remove_ticket_resume_cost_without_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_resume',
            name='cost_without_tax',
            field=models.FloatField(default=0),
        ),
    ]
