# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0005_auto_20170228_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='icon_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon'),
        ),
        migrations.AddField(
            model_name='menu_category',
            name='icon_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='icon_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon'),
        ),
    ]
