# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0005_product_family_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tax', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='complement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_as_complement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='principal',
            field=models.BooleanField(default=True),
        ),
    ]
