# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0006_auto_20170228_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='icon_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Icon'),
        ),
    ]
