# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0006_supply_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='restaurant',
        ),
    ]
