# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0007_remove_supply_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
