# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0007_product_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iva',
            new_name='iva_tax',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_as_complement_with_tax',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_as_complement',
            new_name='price_with_tax',
        ),
        migrations.AlterField(
            model_name='iva',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
