# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0008_auto_20170523_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='cost_of_meal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.TimeField(db_index=True),
        ),
    ]
