# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0008_auto_20170313_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
