# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0011_auto_20170523_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='complement',
            new_name='can_be_complement',
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='isComplement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 5, 23, 15, 23, 33, 495678)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(15, 23, 33, 495719)),
        ),
    ]
