# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0012_auto_20170523_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 5, 23, 15, 23, 38, 476786)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(15, 23, 38, 476827)),
        ),
    ]
