# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0013_auto_20170523_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(15, 32, 39, 786272)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 5, 23, 15, 32, 39, 785368)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(15, 32, 39, 785408)),
        ),
    ]
