# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0015_auto_20170528_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(20, 16, 55, 75872)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 5, 28, 20, 16, 55, 74771)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(20, 16, 55, 74816)),
        ),
    ]
