# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0016_auto_20170528_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(20, 42, 58, 141116)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 6, 9, 20, 42, 58, 140191)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(20, 42, 58, 140236)),
        ),
    ]
