# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainRest', '0018_auto_20170625_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product_class',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(21, 8, 26, 193082)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 6, 26, 21, 8, 26, 192063)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(21, 8, 26, 192115)),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'restaurant')]),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set([('number', 'restaurant')]),
        ),
    ]
