# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 02:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0020_auto_20170626_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ref_staff_rol',
            name='staf_role_description',
            field=models.CharField(choices=[('W', 'Camarero'), ('K', 'Cocinero'), ('B', 'Barman'), ('M', 'Manager')], max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(2, 52, 35, 478442)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 6, 28, 2, 52, 35, 477396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(2, 52, 35, 477443)),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set([('number', 'restaurant', 'type_table')]),
        ),
    ]
