# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0022_auto_20170704_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(16, 48, 56, 73253)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 4, 16, 48, 56, 72319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(16, 48, 56, 72365)),
        ),
    ]
