# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0023_auto_20170704_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref_staff_rol',
            old_name='staf_role_description',
            new_name='staf_role_code',
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(9, 4, 36, 837224)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 6, 9, 4, 36, 836309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(9, 4, 36, 836353)),
        ),
    ]
