# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0026_auto_20170708_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='province',
            field=models.CharField(default='null', max_length=90),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(19, 59, 30, 606387)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 9, 19, 59, 30, 605556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(19, 59, 30, 605588)),
        ),
    ]
