# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0030_auto_20170711_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_role_code',
        ),
        migrations.AddField(
            model_name='staff',
            name='role_code',
            field=models.CharField(choices=[('W', 'Camarero'), ('K', 'Cocinero'), ('B', 'Barman'), ('M', 'Manager')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='supply',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Supply_Category'),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(9, 44, 49, 882628)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 12, 9, 44, 49, 881390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(9, 44, 49, 881435)),
        ),
        migrations.DeleteModel(
            name='Ref_Staff_Rol',
        ),
    ]
