# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0031_auto_20170712_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_storable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(10, 46, 41, 163464)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 12, 10, 46, 41, 162309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(10, 46, 41, 162365)),
        ),
    ]
