# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0032_auto_20170712_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(22, 56, 21, 786755)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 17, 22, 56, 21, 785474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(22, 56, 21, 785532)),
        ),
    ]
