# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0033_auto_20170718_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='mesure_unity',
        ),
        migrations.AddField(
            model_name='supply',
            name='mesure_unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Mesure_Unity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(23, 30, 1, 226064)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 17, 23, 30, 1, 225057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(23, 30, 1, 225110)),
        ),
    ]
