# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0041_auto_20170722_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 7, 24)),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(10, 33, 49, 662063)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date_of_meal',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 24, 10, 33, 49, 661110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time_of_meal',
            field=models.TimeField(db_index=True, default=datetime.time(10, 33, 49, 661160)),
        ),
    ]
