# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0042_auto_20170724_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_resume',
            old_name='cost_of_meal',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='ticket_resume',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='ticket_resume',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='ticket_resume',
            name='date_of_meal',
        ),
        migrations.RemoveField(
            model_name='ticket_resume',
            name='time_of_meal',
        ),
        migrations.AddField(
            model_name='ticket_resume',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 29, 21, 48, 12, 285780, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(21, 48, 12, 285829)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 7, 29)),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time_of_meal',
            field=models.TimeField(default=datetime.time(21, 48, 12, 286734)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
