# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0043_auto_20170729_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_detail',
            name='time_of_meal',
        ),
        migrations.AddField(
            model_name='ticket_detail',
            name='time',
            field=models.TimeField(default=datetime.time(23, 12, 14, 746957)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 7, 29, 23, 12, 14, 745913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(23, 12, 14, 745973)),
        ),
    ]
