# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0045_auto_20170730_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_detail',
            name='sentKitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 8, 14)),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Product'),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time',
            field=models.TimeField(default=datetime.time(16, 20, 17, 670897)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 8, 14)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(16, 20, 17, 669751)),
        ),
    ]
