# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0048_auto_20170815_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_detail',
            name='time',
            field=models.TimeField(default=datetime.time(10, 18, 43, 412510)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(10, 18, 43, 411708)),
        ),
    ]
