# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0049_auto_20170815_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 8, 26)),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainRest.Owner'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRest.Restaurant'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role_code',
            field=models.CharField(choices=[('W', 'Camarero'), ('K', 'Cocinero'), ('B', 'Barman'), ('M', 'Manager')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time',
            field=models.TimeField(default=datetime.time(11, 33, 9, 280345)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 8, 26)),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(11, 33, 9, 279440)),
        ),
    ]
