# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import mainRest.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0050_auto_20170826_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2017, 9, 5)),
        ),
        migrations.AlterField(
            model_name='ticket_detail',
            name='time',
            field=models.TimeField(default=mainRest.models.Ticket_Detail.defaultTime),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='date',
            field=models.DateField(db_index=True, default=mainRest.models.Ticket_Resume.defaultDate),
        ),
        migrations.AlterField(
            model_name='ticket_resume',
            name='time',
            field=models.TimeField(db_index=True, default=mainRest.models.Ticket_Resume.defaultTime),
        ),
    ]
