# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import mainRest.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRest', '0051_auto_20170905_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(db_index=True, default=mainRest.models.Inventory.defaultDate),
        ),
    ]
